name: TEST Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  Workflow_dispatch:

jobs:
  salutations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          echo "Hello, world!"
          sleep 7
          echo "This is a test of the GitHub Actions workflow."
  aurevoir:
    runs-on: ubuntu-latest
    steps:
      - name: say goodbye
        run: |
          echo "#### Waiting to say goodbye ####"
          sleep 10
          echo "Bye Bye!!!"
