name: Listing Password file
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  list-password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List Password file
        run: ./scripts/passwords.sh
